name: Setup SSH

description: Adds ssh keys for current user to machine

inputs:
  github-secret:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - name: "Enable SSH (Click me for login details)"
      uses: seemethere/add-github-ssh-key@v1
      with:
        GITHUB_TOKEN: ${{ inputs.github-secret }}
        activate-with-label: false
