name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout MultiPy
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          set -eux
          pip install usort==0.6.4
          pip install black
          pip install flake8==3.9.0
      - name: Run Lint
        run: |
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          scripts/lint.sh
